ANDROID: mm/huge_memory: fix build after 5.10.267 merge
Fix undeclared identifier 'flags' in split_huge_page_to_list()
after merging 5.10.267's flags param for __split_huge_page().
Vendor tree uses local_irq_disable/ds_queue lock instead of
pgdata->lru_lock, so define dummy flags variable.

Fixes build error:

  mm/huge_memory.c:2808:38: error: use of undeclared identifier 'flags'

Change-Id: I26bc5fd839cd43c35536302393528916574de078
Signed-off-by: akaliorg <alirahsepar199@gmail.com>